import { Mynerve } from "next/font/google";

const mynerve = Mynerve({
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={mynerve.className}>
      <body>{children}</body>
    </html>
  );
}
