import { Mynerve } from "next/font/google";
import HeaderComponent from "./components/Header";
import FooterComponent from "./components/Footer";

const mynerve = Mynerve({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={mynerve.className}>
      <body>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
